services:
  sit_db_dev:
    container_name: sit_db_dev
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: local_db_dev
    ports:
      - 3307:3306
    volumes:
      - mysql_dev_data:/var/lib/mysql

  sit_db_test:
    container_name: sit_db_test
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: local_db_test
    ports:
      - 3308:3306
    volumes:
      - mysql_test_data:/var/lib/mysql

volumes:
  mysql_dev_data:
  mysql_test_data: